// models/task.model.ts
export interface Task {
  Id?: number;  // Made optional - will be generated by server
  Title: string;
  ParentID: number | null;
  Status: 'On-Track' | 'At-Risk' | 'Completed' | 'Delayed';
  Priority: 'Low' | 'Medium' | 'High' | 'Critical';
  DueDate: Date | string;
  
  // Optional fields for future use
  Description?: string;
  AssignedTo?: string;
  EstimatedHours?: number;
  ActualHours?: number;
  CreatedDate?: Date | string;
  CreatedBy?: string;
  LastModifiedDate?: Date | string;
  LastModifiedBy?: string;
  Tags?: string[];
  Attachments?: any[];
  Comments?: any[];
  Dependencies?: any[];
  
  // UI state fields
  children?: Task[];
  expanded?: boolean;
}
