import { Component, inject, OnInit } from '@angular/core';
import { PnPjs } from '../services/PnPjs';
import { FormBuilder, FormGroup, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import { Task } from '../model/task.model';
import { CommonModule } from '@angular/common';
import { TaskNode } from '../components/task-node/task-node';

@Component({
  selector: 'app-projects',
  imports: [CommonModule,TaskNode,FormsModule,ReactiveFormsModule],
  templateUrl: './projects.html',
  styleUrl: './projects.scss',
})
export class Projects implements OnInit {
  pnpjs = inject(PnPjs);
  tasks: Task[] = [];
  taskForm: FormGroup;

  // Status and Priority options matching the model
  statusOptions: Task['Status'][] = ['Pending', 'In-Progress', 'Completed', 'On-Hold'];
  priorityOptions: Task['Priority'][] = ['Low', 'Medium', 'High', 'Critical'];
  properties: (keyof Task)[] = ['Id', 'Title', 'ParentID', 'Status', 'Priority', 'DueDate'];
  constructor(private fb: FormBuilder) {
    this.taskForm = this.fb.group({
      Id: [''],  // Will be set by server
      Title: ['', Validators.required],
      Status: ['', Validators.required],
      Priority: ['', Validators.required],
      DueDate: ['', Validators.required]
      // Optional fields can be added later
    });
  }
  
  ngOnInit() {
    this.pnpjs.allListItems("Projects").then(items => {
      console.log(items);
      this.tasks = this.buildHierarchy(items as Task[]);
    });
  }

  pickSelectedProperties<T extends object>(arr: T[], properties: (keyof T)[]): Partial<T>[] {
    return arr.map(obj => {
      const newObj: Partial<T> = {};
      properties.forEach(prop => {
        if (prop in obj) {
          newObj[prop] = obj[prop];
        }
      });
      return newObj;
    });
  }

  // Build hierarchy from flat data
  buildHierarchy(tasks: Task[]): Task[] {
    const taskMap = new Map<number, Task>();
    const rootTasks: Task[] = [];

    // First pass: create map of all tasks (only tasks with Id)
    tasks.filter(task => task.Id).forEach(task => {
      taskMap.set(task.Id!, { ...task, children: [], expanded: false });
    });

    // Second pass: build hierarchy
    tasks.forEach(task => {
      if (!task.Id) return; // Skip tasks without ID
      
      const currentTask = taskMap.get(task.Id);
      if (task.ParentID === null) {
        rootTasks.push(currentTask!);
      } else {
        const parent = taskMap.get(task.ParentID);
        if (parent) {
          parent.children = parent.children || [];
          parent.children.push(currentTask!);
        }
      }
    });

    return rootTasks;
  }

  // Toggle expand/collapse
  toggleExpand(task: Task): void {
    task.expanded = !task.expanded;
  }

  // Auto-save task changes
  saveTask(updatedTask: Task): void {
    // Only save if task has an ID (already exists in DB)
    if (updatedTask.Id) {
      this.updateTaskInHierarchy(this.tasks, updatedTask);
      console.log('Auto-saving existing task:', updatedTask);
      console.log('Auto-saving existing task:', this.pick(updatedTask, this.properties));
      // this.taskService.updateTask(updatedTask).subscribe(...);
      this.pnpjs.updateListItem("Projects", updatedTask.Id, this.pick(updatedTask, this.properties));
    }
  }

  pick(obj: any, properties: string[]): any {
    const result: any = {};
    
    properties.forEach(prop => {
      if (obj.hasOwnProperty(prop)) {
        result[prop] = obj[prop];
      }
    });
    
    return result;
  }
  // Update task in hierarchy
  updateTaskInHierarchy(tasks: Task[], updatedTask: Task): boolean {
    for (let task of tasks) {
      if (task.Id === updatedTask.Id) {
        Object.assign(task, updatedTask);
        return true;
      }
      if (task.children && task.children.length > 0) {
        if (this.updateTaskInHierarchy(task.children, updatedTask)) {
          return true;
        }
      }
    }
    return false;
  }

  // Add new subtask
  addSubTask(parentTask: Task): void {
    const newTask: Task = {
      // Id is intentionally omitted - will be generated by server
      Title: 'New Task',
      ParentID: parentTask.Id || null,
      Status: 'Pending',
      Priority: 'Medium',
      DueDate: new Date().toISOString().split('T')[0],
      
      // Optional fields with default values
      // Description: '',
      // AssignedTo: '',
      // EstimatedHours: 0,
      // CreatedDate: new Date(),
      // expanded: true  // Expand the new task
    };

    if (!parentTask.children) {
      parentTask.children = [];
    }
    
    parentTask.children.push(newTask);
    parentTask.expanded = true;

    // Placeholder for API call to create task on server
    console.log('Creating new task:', newTask);
    // this.common.addListItem(this.pnp.moduleIndex.account_governance, this.taskForm);
    this.pnpjs.addListItem("Projects", newTask);
    // this.taskService.createTask(newTask).subscribe(createdTask => {
    //   // Update the local task with the server-generated ID
    //   newTask.Id = createdTask.Id;
    // });

    // Auto-focus on the new task's title after it's rendered
    setTimeout(() => {
      // Since new task doesn't have an ID yet, we need another way to focus
      // We'll focus the last child's title input
      const lastChildIndex = parentTask.children!.length - 1;
      const newTaskElement = document.querySelectorAll('.task-item:last-child .title-field input');
      if (newTaskElement.length > 0) {
        (newTaskElement[0] as HTMLElement).focus();
      }
    }, 100);
  }

  // Delete task
  deleteTask(task: Task): void {
    if (confirm('Are you sure you want to delete this task?')) {
      if (task.Id) {
        // Existing task - remove from hierarchy and call API
        this.removeTaskFromHierarchy(this.tasks, task.Id);
        console.log('Delete existing task:', task.Id);
        // this.taskService.deleteTask(task.Id).subscribe(...);
      } else {
        // New task that hasn't been saved yet - just remove from UI
        this.removeNewTaskFromHierarchy(this.tasks, task);
        console.log('Removed unsaved task');
      }
    }
  }

  // Remove task from hierarchy by ID
  removeTaskFromHierarchy(tasks: Task[], taskId: number): boolean {
    for (let i = 0; i < tasks.length; i++) {
      if (tasks[i].Id === taskId) {
        tasks.splice(i, 1);
        return true;
      }
      if (tasks[i].children && tasks[i].children!.length > 0) {
        if (this.removeTaskFromHierarchy(tasks[i].children!, taskId)) {
          return true;
        }
      }
    }
    return false;
  }

  // Remove new task (without ID) from hierarchy
  removeNewTaskFromHierarchy(tasks: Task[], taskToRemove: Task): boolean {
    for (let i = 0; i < tasks.length; i++) {
      // Compare by reference or by other properties since no ID
      if (tasks[i] === taskToRemove) {
        tasks.splice(i, 1);
        return true;
      }
      if (tasks[i].children && tasks[i].children!.length > 0) {
        if (this.removeNewTaskFromHierarchy(tasks[i].children!, taskToRemove)) {
          return true;
        }
      }
    }
    return false;
  }

  // Handle save of new task (called from task-node when server returns ID)
  onTaskCreated(newTask: Task, serverResponse: any): void {
    // Update the task with server-generated ID and other fields
    newTask.Id = serverResponse.Id;
    // Update any other fields returned from server
    console.log('Task created with ID:', newTask.Id);
  }
}
